language: node_js

node_js:
   - node # will use latest node

before_script: # commands to run before the build step
   - ./scripts/setEnv.sh
   - npm install -g --silent @angular/cli

script: # the build step
   - ng build --prod -base-href $BASE_HREF

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_API_KEY
  project: "retromote"
